# Dependencies
gems:              
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-paginate
paginate: 5
paginate_path: "page:num"

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Mirko Mazzoleni
tagline:             'Sharing code and thoughts while working with data science'
description:         'Mirko Mazzoleni data science blog'
url:                 http://mirkomazzoleni.github.io
baseurl:             ''



# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  math_engine: mathjax
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'


# Includes an icon in the footer for each username you enter
footer-links:
  dribbble: 
  email: mirko.mazzoleniphd@gmail.com
  facebook:
  flickr:
  github: mirkomazzoleni
  instagram:
  linkedin:
  pinterest:
  rss: # just type anything here for a working RSS icon
  twitter: MazMko
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/


exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

